name: zuzu nestjs api-server unit test

on:
    pull_request:
        branches: [develop, main]

jobs:
    test:
        runs-on: ubuntu-20.04
        timeout-minutes: 10

        strategy:
            matrix:
                node-version: [16.5]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.3.0
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Create env.test file
              run: |
                  touch .env.test
                  echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env.test
                  echo PORT=${{secrets.PORT}} >> .env.test
                  echo DATABASE_USER=${{secrets.DATABASE_USER}} >> .env.test
                  echo DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} >> .env.test
                  echo DATABASE_HOST=${{secrets.DATABASE_HOST}} >> .env.test
                  echo DATABASE_PORT=${{secrets.DATABASE_PORT}} >> .env.test
                  echo DATABASE_DB=${{secrets.DATABASE_DB}} >> .env.test
                  echo KAKAO_CLIENT_ID=${{secrets.KAKAO_CLIENT_ID}} >> .env.test
                  echo KAKAO_CALLBACK_URL=${{secrets.KAKAO_CALLBACK_URL}} >> .env.test
            - name: Install packages
              run: pnpm install --frozen-lockfile
            - name: Run unit test
              run: pnpm run test
