name: zuzu nestjs unit test

on:
    pull_request:
        branches: [develop, main]

jobs:
    test:
        runs-on: ubuntu-20.04
        timeout-minutes: 10

        strategy:
            matrix:
                node-version: [16.5]

        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7.3.0
            - name: Use Node ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - name: Create env.test file
              run: |
                  touch .env.test
                  echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env.test
                  echo PORT=${{secret.PORT}} >> .env.test
                  echo DATABASE_USER=${{secret.DATABASE_USER}} >> .env.test
                  echo DATABASE_PASSWORD=${{secret.DATABASE_PASSWORD}} >> .env.test
                  echo DATABASE_HOST=${{secret.DATABASE_HOST}} >> .env.test
                  echo DATABASE_PORT=${{secret.DATABASE_PORT}} >> .env.test
                  echo DATABASE_DB=${{secret.DATABASE_DB}} >> .env.test
                  echo POSTGRES_HOST=${{secret.POSTGRES_HOST}} >> .env.test
                  echo POSTGRES_PORT=${{secret.POSTGRES_PORT}} >> .env.test
                  echo POSTGRES_USER=${{secret.POSTGRES_USER}} >> .env.test
                  echo POSTGRES_PASSWORD=${{secret.POSTGRES_PASSWORD}} >> .env.test
                  echo POSTGRES_DB=${{secret.POSTGRES_DB}} >> .env.test
                  echo KAKAO_CLIENT_ID=${{secret.KAKAO_CLIENT_ID}} >> .env.test
                  echo KAKAO_REDIRECT_URL=${{secret.KAKAO_REDIRECT_URL}} >> .env.test
            - name: Install packages
              run: pnpm install --frozen-lockfile
            - name: Run unit test
              run: pnpm test
